# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.BooleanField(default=False, help_text='if true than this user will be active'),
        ),
    ]
