# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0003_auto_20160723_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_celery_run',
            field=models.BooleanField(default=False, help_text='if celery is running this process already'),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.BooleanField(default=False, help_text='if true than this user will be active and will scan his square'),
        ),
    ]
