# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0004_auto_20160726_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(blank=True, help_text='descripe this player, and the area for which he is responsible for', max_length=550, null=True),
        ),
    ]
