# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapview', '0005_player_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_login',
            field=models.IntegerField(blank=True, choices=[(1, 'Success: Login'), (0, 'Failed: Login'), (None, 'Unknown/Inactive')], null=True, verbose_name='login status'),
        ),
    ]
